language: groovy
jdk:
  - oraclejdk8
after_success:
  - ./publish/publish.sh

secure: "Yg21h2zjmrSf3ZklknvoZmKTcn4e1pcT8HQN61kvtSATdC+8Ky4J+/Wos1RBQ4R86quh7TiM8Tb9kbhdbjGGVDVpCJFZtq6b20MQNcNYJ/CRESS8BhCMzW8ahBpXFTya1DJ2y3V9A6yHF7S1BQOTFEnwUBrNTrDJQwSsUX27NzU5kEz+GS+7jaPkxx/Se4rgJZQ5kzTsjBEXz9a1198FjFQsNXQpCFq0RwxRWu/H2T+IIadDrMjCc5z5GVTGmHT/MjWEL8E7Ix30toqHrWN/wT6zOsz8ZbqjxP++Kwe/PK5tXo8zY8wyqQptBUHL5hQYsA94OI2xYbyxcp8809+FJPz2tiN3qG+kRpsBZxpiAD/sTsqr3AKzmxaT1s+qraSKHLL/j2avWMFRlVB0z8Wb8YLa/2UJJgB5Q6+uCDj5ISuJxaldW6/M9n3SSgLonS+pey2WKEu0ouRUP8zGBqKmYMK5gjdqyQGtiRnMhQbagFR0IYQY5nhqqxGy7TelQFEd6w/aslBZCguXjbwR+HEv/IE9OZhh58SLRO+6PcniKONOjd91iNVI2vh53vk7YzVv+1yAGt8gq7LaitrBUcgDXKANZBgQkG2NJ/S4LMYmtfVSC0bc4yKmTpzYfWwx5EJoi5fJgdM2ST634NnCTLZOEUSXl/fcHM3zqyOhoXvEQGA="
