language: groovy
jdk:
  - oraclejdk8
after_success:
  - ./publish/publish.sh

secure: "If5y+HmEyIk3dKeAD3j2ei2EMb+1PRbbOOSKwxo0mI17iTh11LP5R6oET6k8z0/xz5HRQOpsX7mW9NCUmh9P93rfa4rAlhT4hop3vv3fBrvm9PLcwe1Gi8w6YLHffoIgqsMgtQgILRJaKcc4Qk/y49Nx84fVmRyPj9flTDhqkhq/xp6uPpdTZf4G1kPbcRwrXMde3tLN3ApooRSP696IdYXzzItqeoWh7hfCjoYWNGIcY9RxZMLvmuPithTypVnksJIAilT4nzsaaLsgRYDHEJ8AwXoP6inLo7dGF7qHJmmBCgbtG7mtL6QJiVN3N2JvdxEBGW9T8HiwxqDNHvWH+hw1mlQWicRE6YMN5KyaeJx6tKnwcP+UHQpiTmtfe6lZGZhi4FwTkCJ3RRvCVIUzcQjs3Ktjo7kknb+KfzxuFRpaWmJjUGSYPCFegLLBt3+XlbXe1wtUsoQaprpPdQhOvdObEvbIX3hFQdd2DsT1XLHG73xyIA9gmqLKycHVmD/iF0yTImxJDlWIB4fPZHQgRQzKdL11Da4P3LsXR7/UyRyNlR8iWzMoFhYeY4aFYYL/rpI/Aye64jmLod8i94v34/0W13+Fu99rSdhxV2BRfN21ZKQeiOvlK6LfgJY+8Vb+/OSYHS8V5N+/DW5l+SKKZ6ICgx9ALxVFJfG+85ZF1DA="
